name: test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cabal/store
          key: cabal-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: cabal-
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.7'
          cabal-version: '3.6.2.0'
      - run: printf 'bad\tgood\thi\tthere\n' | cabal run
